image: go1.3
env:
    - RETHINKDB_TEST_PORT_28015_TCP_ADDR=127.0.0.1
    - RETHINKDB_TEST_PORT_28015_TCP_PORT=28015
    - RETHINKDB_TEST_DATABASE=shipyard_test
script:
    - go get github.com/tools/godep
    - ln -sf $GOPATH/bin/godep /usr/local/bin/godep
    - pushd controller
    - make test
    - popd
    - pushd cli
    - make test
    - popd
services:
    - shipyard/rethinkdb

